### ISSUE TITLE
Cloze hider (👑) overrides cloze hints in note

### ISSUE THREAD

**Issue by bradydjohnson** [AnKing-VIP/AnKing-Note-Types#146] opened 2023-07-30 23:04 UTC
#### Which Note Type (and version) is this about?
General and Anking Overhaul

#### Problem description

The cloze hider (👑) overrides cloze hints.

<img width="451" alt="AnKing Note Types 2023-07-30 17-51-19" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/6741590/629527e1-c66b-4e9d-8e67-14b89506f71e">

The Anking Note Type settings come with the cloze hider (👑) set as a default.

For example, I added some close hints (::↑,nl,↓) to this card.
![Browse (1 of 1075 cards selected) 2023-07-30 17-54-43](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/6741590/11aa4967-5f21-47be-b983-9b4d8ba8431a)

When previewing/reviewing this card, the cloze hider (👑) overrides the cloze hints (::↑,nl,↓).
<img width="722" alt="Preview 2023-07-30 17-57-15" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/6741590/fab13363-1fda-435a-a3a6-d7fd7299c188">

If you remove cloze hider (👑) from the Note Type settings, then the cloze hints (::↑,nl,↓) still don't show.
<img width="719" alt="Preview 2023-07-30 17-59-41" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/6741590/4895d2ad-08dc-4e60-a386-ce0ff37cf4d9">
 

Also, this is minor but somewhat related: The little speech bubble next to these settings in the Note Types config doesn't appear to do anything. Hovering over it doesn't show any text.
<img width="92" alt="Image 2023-07-30 18-05-21" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/6741590/4b2cc74c-0065-43ed-85df-89060a13a57c">

#### Checklist
 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
```
2.1.65
```

#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
MacOS Ventura 13.4.1

#### Error message (if any)
none

**Comment by AnKingMed** [comment] 2023-07-31 00:02
The hints show for me. Does it work if you just do text for the hint?

**Comment by bradydjohnson** [comment] 2023-08-07 01:21
Possibly. Let me look for a card that it wasn't working for. I think I was using "::↑,nl,↓" as the cloze hint and that wasn't working.

**Comment by bradydjohnson** [comment] 2023-08-07 01:22
<img width="631" alt="Edit Current 2023-08-06 20-21-45" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/6741590/4e63180d-cecd-4976-a711-8010a379ad42">
<img width="569" alt="Brady - Anki 2023-08-06 20-21-57" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/6741590/5fdc6889-3ac6-4289-88e3-46eae4171101">

Seems like "::#" as a close-hint doesn't work.

**Comment by AnKingMed** [comment] 2023-08-07 09:41
@abdnh this seems like a reasonable bug to look into when you have time

**Comment by abdnh** [comment] 2023-08-13 03:09
I'm unable to reproduce this.
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/41397710/4b8bfb29-1445-4e19-b3ee-367eb136408c)
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/41397710/ad5a9ac9-007e-43b4-b5d5-bd802c26bea5)

@bradydjohnson do you perhaps have any other add-on that also modifies clozes?

**Comment by bradydjohnson** [comment] 2023-08-13 03:14
<img width="246" alt="Add-ons 2023-08-12 22-14-10" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/6741590/1881fdbb-22df-4394-b590-14a59a823436">

**Comment by abdnh** [comment] 2023-08-13 03:39
Try running Anki with add-ons disabled temporarily: https://faqs.ankiweb.net/when-problems-occur.html

**Comment by laf72** [comment] 2023-09-18 18:18
![Crown in clozes 9-17-23](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/9941657/4cfe54ea-b7e1-4481-9788-38b36af83df8)
I also had this same issue in a card yesterday.  I had to make a new card and copy and paste the card text from AnkiHub as plain text to remove the crown emojis.  Editing the text or copying and pasting straight from AnkiHub into the same card still resulted in the crown emojis.  I didn't know what they were (I only got AnkiHub on Sept 16).

**Comment by AnKingMed** [comment] 2023-09-19 00:10
@laf72 is this a one by one note? When you edit the card, is there a "one by one" field with some text in it?

**Comment by laf72** [comment] 2023-09-19 11:33
> @laf72 is this a one by one note? When you edit the card, is there a "one by one" field with some text in it?

I think so?  Sorry, I deleted the original note in my set and the new card is a "One by One".  I have pushed the suggestion to AnkiHub with the explanation, but wanted to add this picture to this issue.  The original card id is 1515539356519

**Comment by AnKingMed** [comment] 2023-09-20 00:17
I think you may have an old version of my note type. Make sure you have the latest version of the AnKing Note Types. Also watch this video as it will explain a lot: https://youtu.be/NYUhNMyAZNs

**Comment by aly-k** [comment] 2023-11-27 11:08
i have the same issue on ankidroid 2.16.5 when using "anking overhaul" one by one notes with hints and `autoflip to answer` enabled. The same card behaves normally and correctly displays the hint on anki desktop 23.10.1

i am using the latest anking overhaul notetype version from the addon `version 6c9041e `

## steps to reproduce
1. use the latest version of "anking overhaul" notetype
2. set `var autoflip = true`
3. create a cloze one by one note with hints
4. confirm correct behaviour on anki desktop
5. check behaviour on ankidroid (op also reported same behaviour on ios)
you should now see that hints do NOT show and are replaced by 👑 cloze hider

**Comment by AnKingMed** [comment] 2023-11-27 11:27
@abdnh are you able to replicate this on Ankidroid? I only have ios

**Comment by abdnh** [comment] 2023-11-29 13:02
Yes, I can reproduce it on AnkiDroid. Will look into it.

**Comment by abdnh** [comment] 2023-11-29 14:15
Fixing this will require integrating a script like this: https://github.com/SimonLammer/anki-persistence

Other AnkiDroid-specific issues in the notetypes might be fixed by this too.

Reference: https://github.com/ankidroid/Anki-Android/issues/4828

**Comment by aly-k** [comment] 2023-11-29 16:40
i can confirm that the fix works

**Closed** 2024-01-16 21:50 UTC
Labels: bug
